name: Test

on: [push, pull_request]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.6.0' # default is 'stable'

      - name: Install Packages
        run: nimble install -y

      - name: Write index.html
        run: nim c -r fetchbook.nim
  
      - name: Archive API docs
        uses: actions/upload-artifact@v2
        with:
          name: api-docs
          path: |
            docs/api
  deploy-docs:
    needs:
      - prepare
    runs-on: ubuntu-latest
    steps:
      - name: Download all docs
        uses: actions/download-artifact@v2

      - name: Check files
        run: |
          find .
      - name: Setup docs
        run: |
          mv api/ docs/
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          target_branch: gh-pages
          build_dir: ./docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
